apiVersion: v1
kind: Service
metadata:
  name: nginx-app-service
  namespace: default
spec:
  selector:
    app: nginx-example
  type: NodePort
  ports:
  - name: nginx-app-service
    port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30000